### DISCUSSION TITLE
What is environment variables for COLD , KES , VRF keys ?

### DISCUSSION THREAD

**Discussion by jackchuong** [IntersectMBO/cardano-node#5822] [Q&A]
Hi all,
If I want to run cardano node (block producer) by docker compose like below:
```
version: '3.1'

services:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:1.35.7
    container_name: cardano-node
    volumes:
      - ./cardano-node-ipc:/ipc
      - ./cardano-node-data:/data
      - ./configuration:/configuration
      - ./cardano-wallet:/cardano-wallet
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - CARDANO_CLI=/cardano-wallet/cardano-cli
      - DOCKER_CLIENT_TIMEOUT=120
      - COMPOSE_HTTP_TIMEOUT=120
      - NETWORK=preprod
      - HOST-ADDR="0.0.0.0"
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - cardano-node-net

networks:
  cardano-node-net:
    name: cardano-node-net
    driver: bridge
```
What is environment variables for COLD , KES , VRF keys ?
