### ISSUE TITLE
[BUG] - testnet preprod network testnet-magic 1 does not exist

### ISSUE THREAD

**Issue by jackchuong** [IntersectMBO/cardano-node#5649]
**Internal/External**
*External*   otherwise.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
Hi all,
I used to run cardano node testnet preprod in docker successfully , here my docker-compose.yml
```
version: '3.1'

services:
  cardano-node:
    image: inputoutput/cardano-node:1.35.5
    container_name: cardano-node
    volumes:
      - ./cardano-node-ipc:/ipc
      - ./cardano-node-data:/data
      - ./configuration:/configuration
      - ./cardano-wallet:/cardano-wallet
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - CARDANO_CLI=/cardano-wallet/cardano-cli
      - DOCKER_CLIENT_TIMEOUT=120
      - COMPOSE_HTTP_TIMEOUT=120
      - NETWORK=--testnet-magic 1
      - HOST-ADDR="0.0.0.0"
    restart: unless-stopped
    networks:
      - cardano-node-net

networks:
  cardano-node-net:
    name: cardano-node-net
    driver: bridge
```
But now container cannot start and I get error
```
docker logs -f cardano-node
[Error] Managed configuration for network --testnet-magic 1 does not exist
[Error] Managed configuration for network --testnet-magic 1 does not exist
[Error] Managed configuration for network --testnet-magic 1 does not exist
[Error] Managed configuration for network --testnet-magic 1 does not exist
```

**Steps to reproduce**
1. `docker compose -f docker-compose.yml up -d`
2. 
```
docker ps -a
CONTAINER ID   IMAGE                             COMMAND                  CREATED          STATUS                                  PORTS                                                                      NAMES
e69452ee1c4a   inputoutput/cardano-node:1.35.5   "entrypoint"             11 seconds ago   Restarting (1) Less than a second ago                                                                              cardano-node
```
3. 
```
docker logs -f cardano-node
[Error] Managed configuration for network --testnet-magic 1 does not exist
[Error] Managed configuration for network --testnet-magic 1 does not exist
[Error] Managed configuration for network --testnet-magic 1 does not exist
```

**Expected behavior**
container cardano-node up and running

**System info (please complete the following information):**
- OS Name: [e.g. Ubuntu]
- OS Version [e.g. 20.04]
- Node version 1.35.5
- CLI version  1.35.4 - linux-x86_64 - ghc-8.10

I have tried NETWORK=–testnet-magic 2 or NETWORK=–testnet-magic 1 , still same error
Is there something wrong with the preprod/preview network ?
Please give me some advice, thank you very much.

**Comment by carbolymer** [comment]
You appear to be using some old image. Can you try this one: https://github.com/intersectmbo/cardano-node/pkgs/container/cardano-node/?tag=8.7.3 ?

**Comment by jackchuong** [comment]
@carbolymer I tried as below
```
version: '3.1'

services:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:8.8.0-pre-test-sg-1
    container_name: cardano-node
    volumes:
      - ./cardano-node-ipc:/ipc
      - ./cardano-node-data:/data
      - ./configuration:/configuration
      - ./cardano-wallet:/cardano-wallet
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - CARDANO_CLI=/cardano-wallet/cardano-cli
      - DOCKER_CLIENT_TIMEOUT=120
      - COMPOSE_HTTP_TIMEOUT=120
      - NETWORK=--testnet-magic 1
      - HOST-ADDR="0.0.0.0"
    restart: unless-stopped
    networks:
      - cardano-node-net

networks:
  cardano-node-net:
    name: cardano-node-net
    driver: bridge
```
I still get same error, please note that I downloaded configuration files from https://book.world.dev.cardano.org/env-preprod.html
If I use `inputoutput/cardano-node:1.35.5` with `NETWORK=mainnet`  (with configuration files downloaded properly from https://book.world.dev.cardano.org/env-mainnet.html), it works fine.
